# Generated by Django 3.2.9 on 2022-06-17 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0002_alter_resumetemplate_template_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='resume_template',
        ),
    ]
