# Generated by Django 3.2.9 on 2022-06-23 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0004_alter_resumetemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='resume_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resumesite.resumetemplate'),
            preserve_default=False,
        ),
    ]
