# Generated by Django 3.2.9 on 2022-06-23 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0005_cv_resume_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='resume_template',
        ),
    ]
