# Generated by Django 3.2.9 on 2022-06-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0006_remove_cv_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='fieldstudy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специальность'),
        ),
    ]
