# Generated by Django 3.2.9 on 2022-06-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumesite', '0007_alter_education_fieldstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='resume_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название резюме'),
            preserve_default=False,
        ),
    ]
